#!/bin/sh
#Configurations injected by install_server below....

EXEC=/usr/sbin/ttl_iptables
PIDFILE=/var/run/ttl_iptables.pid
###############
# SysV Init Information
# chkconfig: - 58 74
# description: ttl_iptables daemon.
### BEGIN INIT INFO
# Provides: ttl_iptables
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: ttl_iptables daemon
### END INIT INFO


case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting ttl_iptables server..."
            $EXEC 
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            kill $(cat $PIDFILE)
            echo "Stopping ..."
        fi
        ;;
    status)
	 
        if [  -f $PIDFILE ]
	then
             PID=$(cat $PIDFILE)
        	if [ ! -x /proc/${PID} ]
        	then
            		echo 'ttl_iptables is not running'
        	else
            		echo "ttl_iptables is running ($PID)"
                fi
        else 
		 echo 'ttl_iptables is not running'
 	fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
